name: Daily job for continuous training

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Poetry
        run: |
          pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.7"
          cache: poetry

      - name: Install dependencies
        run: |
          poetry install --no-root --no-dev

      - name: Run train script
        run: |
          poetry run python src/models/train.py
        env:
          MONOGDB_URL: ${{ secrets.MONGODB_URL }}

